services:
  db:
    image: postgres:15
    container_name: imdb_postgres
    environment:
      POSTGRES_USER: imdb
      POSTGRES_PASSWORD: imdb
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./queries:/queries
