services:
  db:
    image: postgres:15
    container_name: imdb_postgres
    environment:
      POSTGRES_USER: imdb
      POSTGRES_PASSWORD: imdb
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./queries:/queries
      - ./data:/imdb_data
    command: [
      "postgres",
      "-c", "shared_buffers=512MB",
      "-c", "work_mem=64MB", 
      "-c", "maintenance_work_mem=512MB",
      "-c", "max_wal_size=2GB",
      "-c", "min_wal_size=1GB",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "fsync=off",
      "-c", "synchronous_commit=off",
      "-c", "full_page_writes=off"
    ]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U imdb" ]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  imdb_data: